/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gym;

/**
 *
 * @author ELIFE STORE
 */
public class all extends javax.swing.JFrame {

    /**
     * Creates new form all
     */
    public all() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customerbtn = new javax.swing.JButton();
        coachbtn = new javax.swing.JButton();
        exercisebtn = new javax.swing.JButton();
        machinbtn = new javax.swing.JButton();
        subscribebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(910, 700));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(null);

        customerbtn.setBackground(new java.awt.Color(255, 153, 51));
        customerbtn.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        customerbtn.setText("CUSTOMERs");
        customerbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        customerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerbtnActionPerformed(evt);
            }
        });
        jPanel1.add(customerbtn);
        customerbtn.setBounds(280, 60, 320, 70);

        coachbtn.setBackground(new java.awt.Color(204, 204, 204));
        coachbtn.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        coachbtn.setText("COACHes");
        coachbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coachbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachbtnActionPerformed(evt);
            }
        });
        jPanel1.add(coachbtn);
        coachbtn.setBounds(280, 180, 320, 70);

        exercisebtn.setBackground(new java.awt.Color(204, 204, 204));
        exercisebtn.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        exercisebtn.setText("EXERCISEs");
        exercisebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exercisebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exercisebtnActionPerformed(evt);
            }
        });
        jPanel1.add(exercisebtn);
        exercisebtn.setBounds(280, 400, 320, 70);

        machinbtn.setBackground(new java.awt.Color(255, 153, 0));
        machinbtn.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        machinbtn.setText("MACHINEs");
        machinbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        machinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machinbtnActionPerformed(evt);
            }
        });
        jPanel1.add(machinbtn);
        machinbtn.setBounds(280, 290, 320, 70);

        subscribebtn.setBackground(new java.awt.Color(255, 153, 0));
        subscribebtn.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        subscribebtn.setText("MEMBERSHIP");
        subscribebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subscribebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribebtnActionPerformed(evt);
            }
        });
        jPanel1.add(subscribebtn);
        subscribebtn.setBounds(280, 500, 320, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 960, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coachbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachbtnActionPerformed
    coach f3 = new coach();
f3.setVisible(true);
f3.RemovePanels();
f3.setDefaultCloseOperation(EXIT_ON_CLOSE);
f3.setResizable(false);
f3.show();
dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_coachbtnActionPerformed

    private void machinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machinbtnActionPerformed
 machine f4 = new machine();
f4.setVisible(true);
f4.RemovePanels();
f4.setDefaultCloseOperation(EXIT_ON_CLOSE);
f4.setResizable(false);
f4.show();
dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_machinbtnActionPerformed

    private void customerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerbtnActionPerformed
   customer f2 = new customer();
f2.setVisible(true);
f2.RemovePanels();   
f2.setDefaultCloseOperation(EXIT_ON_CLOSE);
f2.setResizable(false);
f2.show();
dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_customerbtnActionPerformed

    private void exercisebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exercisebtnActionPerformed
exercise f5 = new exercise();
f5.setVisible(true);
f5.RemovePanels();
f5.setDefaultCloseOperation(EXIT_ON_CLOSE);
f5.setResizable(false);
f5.show();
dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_exercisebtnActionPerformed

    private void subscribebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribebtnActionPerformed
membership f6 = new membership();
f6.setVisible(true);
f6.RemovePanels();
f6.setDefaultCloseOperation(EXIT_ON_CLOSE);
f6.setResizable(false);
f6.show();
dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_subscribebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new all().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coachbtn;
    private javax.swing.JButton customerbtn;
    private javax.swing.JButton exercisebtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton machinbtn;
    private javax.swing.JButton subscribebtn;
    // End of variables declaration//GEN-END:variables
}
